apiVersion: v1
kind: Service
metadata:
  name: k8stimeservice-service
spec:
  type: NodePort
  selector:
    app: k8stimeservice
    version: green # Initially routing traffic to Blue Pods
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
